### ISSUE TITLE
Loader-related PRs required for release 

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#541]
This issue collects the loader-related PRs both here and in `specutils` that need to be finished and merged in order to provide new loader functionality. They are listed in the order in which they should be merged:

- [ ] Move data loaders to `specutils` and add priorities (https://github.com/astropy/specutils/pull/376)
- [ ] Remove data loaders from `specviz` and handle priorities (#527)
- [ ] Add JWST data loader to `specutils` and load multiple spectra (https://github.com/astropy/specutils/pull/381)
- [ ] Support loading of multiple spectra in `specviz` (#537)
- [ ] Add/update `specviz` loader wizard (#517)

The long pole right now is https://github.com/astropy/specutils/pull/376, specifically the implementation of tests. It seems like a bit of infrastructure is required in order to use test data, so I wonder if we would be okay with mocking test data files in the short term.

**Comment by drdavella** [comment]
https://github.com/spacetelescope/specviz/issues/541 is now merged as well.

**Comment by SaOgaz** [comment]
astropy/specutils#537 and astropy/specutils#517 also merged.

**Comment by hcferguson** [comment]
@drdavella okay to close?

**Comment by drdavella** [comment]
@hcferguson yes, I think we're up-to-date now.
