### ISSUE TITLE
User Documentation Screenshots

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#664]
During the review of #645 @nluetzge and @gderosa2004 suggested improvements to the screenshots in the user documentation. Here a list of improvements that were discussed:

### Tasks:
- [ ] Review and produce better screenshots using builtin Mac OS screenshot tools:
    > - just a tiny little form thing. Can we make the screenshots nicer? With this I mean not to cut them out from a bigger screen shot but just making a dedicated screenshot of this window (so it gives you a nice shadow) like this:
    > <img width="867" alt="screen shot 2019-02-04 at 6 51 53 pm" src="https://user-images.githubusercontent.com/24398824/52245087-2e6fa500-28ae-11e9-8dc2-1505ef470f7c.png">

- [ ]  Focus on dialog pop up boxes:

    > * **Unit conversion**: relevant pop-up windows difficult to read, they also get lost with all the rest of the info in the screenshots

- [ ]  Update filenames and data names in screenshots such that they are easily referred in the documentation 

    > * screenshots should have filenames that are easy to read and to refer to (e.g. spectrum1, spectrum2) not our testing filenames.
    

    > * offer more examples with screenshots

- [ ] Screenshot of disabled data item:

    > * **Plots**:  "Any data that cannot be added to a plot will show as disabled in the data list." refer to plot above and give concrete examples
